### ISSUE TITLE
Practica_Planificacion de recursos

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista#1]
[PRACTICA Planeacion de recursos.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista/files/7517964/PRACTICA.Planeacion.de.recursos.pdf)

**Comment by dulce-blm** [comment]
[Practica_Gestión de los riesgos.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista/files/7565768/Practica_Gestion.de.los.riesgos.pdf)

**Comment by Edwin-1012** [comment]
Cumple con los lineamientos establecidos dentro del proyecto, de igual manera dentro del Sprint 3.
Calificación: 100
Porcentaje: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
